### ISSUE TITLE
NameError: name 'url' is not defined after PR #47

### ISSUE THREAD

**Issue by bccrisan** [Akhliskun/firefox-infra-changelog#49]
After the merge in PR https://github.com/Akhliskun/firefox-infra-changelog/commit/be7b8fcddab666946e921f0edee75e71295d0ddf was done, the code brakes with "NameError: name 'url' is not defined"

**To Reproduce**
Simply run the script and something like
`
Traceback (most recent call last):
  File "E:/bcrisan/repos/fic2/client.py", line 187, in <module>
    create_md_table(repository_name)
  File "E:/bcrisan/repos/fic2/client.py", line 41, in create_md_table
    "|" + date + '\n'
NameError: name 'url' is not defined
`
should pop out.

**Expected behavior**
The script should run and create the md/json files in repositories.

**Desktop (please complete the following information):**
 - OS: Windows 
 - Browser: not applicable
 - Version: master branch (https://github.com/Akhliskun/firefox-infra-changelog)

**Additional context**
Not required.

**Comment by bccrisan** [comment]
Fixed by commit 1377ab077b158342010b44c8cd51556c44ba8100
